application:
  max-allowed-books: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: cotel
    password: cotel
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

