application:
  max-allowed-books: 3


spring:
  datasource:
    url: jdbc:mysql://localhost:8081/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
